# Generated by Django 2.2.10 on 2020-04-18 12:16

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_security_group(_apps, schema_editor):
    db_alias = schema_editor.connection.alias

    group, _created = Group.objects.using(db_alias).get_or_create(name="PyWave User")
    group.permissions.set(
        Permission.objects.filter(codename__in=["view_forecast", "view_spot",])
    )


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [migrations.RunPython(create_security_group, lambda a, s: None)]
