# Generated by Django 2.2.10 on 2020-04-19 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0003_surfer")]

    operations = [
        migrations.AlterField(
            model_name="surfer",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Full name"
            ),
        ),
        migrations.AlterField(
            model_name="surfer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
