# Generated by Django 2.2.10 on 2020-04-19 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0003_surfer")]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "surfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="users.Surfer",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookPayload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL path which received the webhook",
                        null=True,
                        verbose_name="Webhook Path",
                    ),
                ),
                (
                    "payload",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="JSON payload of the received webhook",
                        null=True,
                        verbose_name="Webhook Payload",
                    ),
                ),
                (
                    "headers",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="Request headers of the received webhook",
                        null=True,
                        verbose_name="Webhook Headers",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "twilio_message_id",
                    models.CharField(max_length=64, verbose_name="Twilio's Message ID"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=16,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=16,
                        verbose_name="Message Direction",
                    ),
                ),
                (
                    "content_url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Message content URL",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message content text"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="messaging.Conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
