# Generated by Django 2.2.10 on 2020-04-17 03:51
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    operations = [
        CreateExtension("postgis"),
    ]
